# Este archivo ya no es necesario. Migrado a docker-compose.yml para Docker.
version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=upds_practicas
      - MYSQL_USER=upds
      - MYSQL_PASSWORD=upds123
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
